INSERT [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (N'a5c73f36-52f9-4c5b-93e5-540a0c1a3258', N'admin', N'admin', N'06ab52e2-d589-48fc-b2eb-ef55dae665dc')
GO
INSERT [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'415b4b1a-f3a9-47c1-b65e-b1d8d56e971b', N'admin@smiledental.com', N'ADMIN@SMILEDENTAL.COM', N'admin@smiledental.com', N'ADMIN@SMILEDENTAL.COM', 1, N'AQAAAAEAACcQAAAAEJ3t1xE2GvMRhoA5uFTDj3ZEySTRkdNCrNFnoflUH6fO5fGM3RYTRIpUrHlQX9jELQ==', N'USMIPDQS5WX6DGJDX4KFZA76QO2MSMTH', N'e9de4d05-5b96-4672-bc4c-b2abcbe434c1', NULL, 0, 0, NULL, 1, 0)
GO
INSERT [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'69482454-c12e-48d9-a97c-631d77d4b009', N'emma@gmail.com', N'EMMA@GMAIL.COM', N'emma@gmail.com', N'EMMA@GMAIL.COM', 1, N'AQAAAAEAACcQAAAAEOBwJlqiacrV16XmSYWZziHFDHKZpDDM2QjHfdCxJSDVBbkR3T0inJ+CcpR6GSqiDQ==', N'V2CJMQJFD4X2EKPP5IKO3BK2P23LFCVL', N'18cbd14c-82f8-4af0-a124-51da2716d6b4', NULL, 0, 0, NULL, 1, 0)
GO
INSERT [dbo].[AspNetUserRoles] ([UserId], [RoleId]) VALUES (N'415b4b1a-f3a9-47c1-b65e-b1d8d56e971b', N'a5c73f36-52f9-4c5b-93e5-540a0c1a3258')
GO
SET IDENTITY_INSERT [dbo].[Branches] ON 
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (1, N'Albany Dentists', N'North Shore 119 Apollo Drive Albany 0632', N'0800 476 453')
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (2, N'Papakura Dentists', N'South 6-18 O''Shannessey Street, Papakura, 2110', N'0800 476 453')
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (3, N'Henderson dentists', N'West 6-8 Pioneer St, Henderson, Auckland 0612', N'0800 476 453')
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (4, N'Manukau dentists', N'South 18 Manukau Station Rd, Manukau, 2104', N'0800 476 453')
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (5, N'Sylvia Park dentists', N'Central 286 Mt Wellington Highway, Shop N219, Upper Level, Mt Wellington, 1060', N'0800 476 453')
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (6, N'Somerville dentists', N'East Unit D1 119 Meadowland Dr, Somerville, 2014', N'0800 476 453')
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (7, N'Avondale dentists', N'West 256 Rosebank Rd, Avondale, 1026', N'0800 476 453')
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (8, N'Remuera Dentists', N'Central Unit D1 119 Meadowland Dr, Somerville, 2014', N'0800 476 453')
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (9, N'Ranui dentists', N'Central 419 Swanson Road, Ranui, Auckland 0612', N'0800 476 453')
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (10, N'Auckland City dentists - CBD', N'Auckland City 280 Queen St, CBD, Auckland 0101', N'0800 476 453')
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (11, N'Takanini dentists', N'South 30 Walters Rd, Takanini 2112', N'0800 476 453')
GO
INSERT [dbo].[Branches] ([BranchID], [BranchName], [BranchAddress], [BranchContactNo]) VALUES (12, N'Mangere dentists', N'South 359 Massey Road, Mangere East, Auckland 2024', N'0800 476 453')
GO
SET IDENTITY_INSERT [dbo].[Branches] OFF
GO
SET IDENTITY_INSERT [dbo].[Appointments] ON 
GO
INSERT [dbo].[Appointments] ([AppointmentID], [Name], [Age], [AppointmentDate], [UserID], [ContactNo], [ReasonForVisit], [BranchID]) VALUES (1, N'Sophie Hunt', 25, CAST(N'2021-05-28T00:13:00.0000000' AS DateTime2), N'emma@gmail.com', N'+64-255-556-81', N'Regular visit for checking', 1)
GO
INSERT [dbo].[Appointments] ([AppointmentID], [Name], [Age], [AppointmentDate], [UserID], [ContactNo], [ReasonForVisit], [BranchID]) VALUES (2, N'Vicky Stark', 32, CAST(N'2021-05-21T00:16:00.0000000' AS DateTime2), N'emma@gmail.com', N'+64-280-555-56', N'For Root Canaling', 3)
GO
SET IDENTITY_INSERT [dbo].[Appointments] OFF
GO
SET IDENTITY_INSERT [dbo].[Dentists] ON 
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (1, N'Dr. Cynthia Shi', N'Dentist', N'Bachelor of Dental Surgery - Otago', N'English, Mandarin, Korean', N'General dentistry, Cosmetic dentistry and Fixed Prosthodontics', N'Cynthia graduated from University of Otago with Bachelor of Dental Surgery. Born and raised in China, she is able to communicate in English, mandarin and Korean fluently. Cynthia’s focus is to deliver patient‐centred care and build a trusting relationship with her patients. She enjoys all aspects of dentistry, with special interests in cosmetic dentistry and Fixed Prosthodontics. In order to keep her knowledge and skills up to date, she always attend courses and conferences. Apart from dentistry, Cynthia loves traveling, watching movies, singing and dancing.', N'.jpg')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (2, N'Dr. Yu-Chen Hsiao', N'Dentist', N'Bachelor of Dental Surgery - Otago', N'Mandarin, Hokkien', N'Cosmetic Dentistry and Fixed Prosthodontics', N'Yu-Chen is originally from Kaohsiung, Taiwan and is fluent in both Mandarin and Hokkien. She graduated from University of Otago with Bachelor of Dental Surgery. She is dedicated in providing dental care in a gentle and caring manner. Patient opinion is of utmost importance in her considerations when treatment planning as well as the patient’s best interest. She has special interests in Cosmetic Dentistry and Fixed Prosthodontics. In her spare time she likes to read, handcraft and enjoy sports such as kayaking and horse riding.', N'.png')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (3, N'Dr. Sam So', N'Dentist', N'Bachelor of Dental Surgery - University of Otago', N'English and Korean', N'General and cosmetic dentistry, minor oral surgery (wisdom extraction).', N'Before joining Smile Dental, He used to work in Hamilton for several years before coming up to Auckland. He’s passionate about delivering tailored care and to provide stress-free dental experience for each patient', N'.jpeg')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (4, N'Dr. Samson Looi', N'Dentist', N'Bachelor of Dental Surgery – Otago', N'English, Mandarin, Cantonese, Malay language.', N'General dentistry, Restorative & Cosmetic dentistry, Minor oral surgery.', N'Samson is aware that New Zealand is becoming more ethnically diverse. Malaysian by birth, he is able to converse in English, Mandarin, Cantonese and Malay language. He is also sensitive to cultural differences. He graduated with a Bachelor of Dental Surgery (BDS) from the University of Otago. He practices general dentistry and has a special interest in restorative & cosmetic dentistry. He believes great dentistry is accomplished by accurate diagnosis and treatment planning. Samson is a coffee addict and a technology freak. Besides dentistry, he enjoys photography and tramping. Running keeps him alive and he completed his first half marathon in 2015.', N'.jpg')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (5, N'Dr. Jasmine Yeo', N'Dentist', N'Bachelor of Dental Surgery - Otago', N'English', N'General and cosmetic dentistry', N'Jasmine was born and raised in Auckland and graduated from the University of Otago with a Bachelor of Dental Surgery. Her goal as a dentist is to help people feel at ease when they come in, and many patients appreciate her gentle nature in making their visit a pleasant experience. Jasmine is passionate about involving patients in their own oral health through discussing the available treatment options, encouraging them to ask any questions they may have and valuing their opinions and decisions. She enjoys all aspects of dentistry with a special interest in preventative and restorative dentistry, keeping up to date with new research by attending courses throughout New Zealand and Australia. Outside of work Jasmine enjoys spending time with family and friends, as well as painting and cooking. ', N'.jpg')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (6, N'Dr. Kevin Koay', N'Dentist', N'Bachelor of Dental Surgery - Otago', N' English, Hokkien, Malay', N'General dentistry, Restorative dentistry, Oral surgery', N'I am thoroughly honoured to be able to contribute to society and to be an advocate for good oral health. I believe in going the extra mile to make my patients smile. I value patients’ opinions and cater to their treatment needs. I believe in making the workplace a more relaxed and casual environment. I have a particular interest in restorative dentistry and oral surgery. Blessed with the chance to practice dentistry in both Malaysia and New Zealand, I believe it has provided me with adequate exposure to manage patients coming from diverse cultural backgrounds, therefore allowing a more holistic approach during treatment. Aside from dentistry, I grew up playing competitive tennis and the sport has always been a big part of my life. Lastly, being a regular at the gym allows me to keep fit and healthy.', N'.jpg')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (7, N'Dr. Chloe Oon', N'Dentist', N'Bachelor of Dental Surgery - Otago', N'English, Mandarin, Malay', N' General and cosmetic dentistry, Oral surgery, Root canal therapy', N'Graduated with Bachelor of Dental Surgery from the University of Otago, Chloe practices all aspects of general dentistry with a special interest in restorative and cosmetic dentistry. She worked in Hamilton before relocating to Auckland to join Smile Dental. Chloe believes in achieving patients’ satisfactions by delivering quality dental care. She explains and demystifies treatment plans patiently, providing a comprehensive understanding of what is required for patients’ specific needs. In order to be up-to-date and to be able to offer her patients the most current treatment options available, Chloe continues to polish her skills by attending dental conference and hands-on courses. Born in Malaysia, Chloe is conversant in English, Mandarin and various Chinese dialects. Aside from Dentistry, Chloe enjoys yoga, nature walks and photography.', N'.jpg')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (8, N'Dr. Ali Han', N'Dentist', N'Bachelor of Dental Surgery - Otago', N'English, Korean', N'Cosmetic dentistry, metal braces, clear aligners (Invisalign)', N'Dr. Ali Han is a caring and gentle clinician who believes that the trip to the dentist should be a positive experience. She takes care to listen to the concerns and desires of her patients and works together to find the best solution for their circumstances. Fluent in English and Korean, Ali is an Aucklander who also spent some time in South Korea and the USA during childhood. She was awarded the Craddock Prize in Complete Removable Prosthodontics during her dental degree. She practices all aspects of general dentistry with an interest in conservative dentistry, cosmetic dentistry and orthodontics. When not in the office, Ali enjoys spending time with her friends and family and keeping fit through Pilates', N'.jpg')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (9, N'Dr. Andy Liu', N'Dentist', N'Bachelor of Dental Surgery - Otago', N'English, Mandarin', N'Not Mention', N'I am originally from Taiwan (fluent in Mandarin), and immigrated to New Zealand at a young age. I grew up in Auckland, and attended the University of Otago where I received my Bachelor of Dental Surgery with Distinction. I enjoy all aspects of dentistry, especially when I can help empower patients to take control of their oral health. I take pride in my open communication with patients to truly understand their wants and needs in order to provide them with the best possible care. Aside from dentistry, I spend my time looking after the newest member of my family, Popcorn, my puppy Bichon Frise. In addition I like to cook with my friends and family, to enjoy good food and great company.', N'.jpg')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (10, N'Dr. Annie Han', N'Dentist', N' Bachelor of Dental Surgery (Otago)', N'English, Korean', N'Fixed Prosthodontics and Cosmetic Dentistry', N'Dr Annie recieved her Bachelor of Dental Surgery degree from the University of Otago. With her friendly and caring nature, she aims to make visits to the dentist a more pleasing experience. She understands that everyone’s needs are different and places a great importance in including her patient’s opinions during the treatment planning phase. Annie practices all aspects of dentistry, with special interests in Fixed Prosthodontics and Cosmetic Dentistry.  Having spent her childhood in the United States and South Korea, she is fluent in both English and Korean. Outside of work, Annie enjoys water-sports, like kayaking and swimming. ', N'.jpg')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (11, N'Dr. Jyothi Dravid', N'Dentist', N'Bachelor of Dentistry ; Master of Oral Surgery', N'English', N'Oral surgery, Restorative dentistry, Prosthodontics.', N'Jyothi graduated with a Bachelor of Dentistry from India in 1990.Then pursued her interest in Oral Surgery, getting her Masters in Oral Surgery in India. She worked in a multispecialty hospital in India for 3 years. After moving to New Zealand, Dr. Jyothi got her NZDREX registration to practice here in 1997. Dr. Jyothi has since been working as a dental practitioner at Smile Dental for the last 18 years with great interest in all aspects of Dentistry. Communication is the key to success. She is very good in her communication to all ages, understanding their needs and explaining the different options to achieve the best results in their dental care. She takes great pride in providing quality dental care to her patients and has established a long term relationship with her patients. Her friendly and caring nature is appreciated by many patients as she puts them at ease and makes the visit to the dentist a more pleasing experience. She continues to keep herself updated by attending continuing education courses and conferences. Outside dentistry she enjoys travelling, cooking and reading. Sketching caricatures is also her hobby.', N'.jpg')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (12, N'Dr. Richelle Tan', N'Dentist', N'Bachelor of Dental Surgery', N'English, Mandarin, Cantonese, Malay', N'General dentistry, Cosmetic dentistry, Oral surgery, Root canal treatment', N'Richelle graduated from the University of Otago in 2015 with a degree in Bachelor of Dental Surgery. She worked with a private practice in Napier, before relocating to Auckland to join Smile Dental. Born and raised in Malaysia, she is able to communicate in English, Mandarin, Cantonese and Malay. Richelle has always wanted to make a positive change in people’s lives, and dentistry is definitely a good place to start. With an encouraging and caring approach, she has put many nervous patients at ease when they are in the dental chair. She enjoys all aspects of dentistry, with special interests in minimally invasive dentistry as well as cosmetic dentistry. In order to provide her patients with a high quality of care, she also keeps up to date with latest dental technology and knowledge by attending conferences, training and courses regularly. Outside of dentistry, she enjoys watching movies, baking, traveling and hiking.', N'.jpg')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (13, N'Dr. Manish Latch', N'Dentist', N'University of Otago', N'English', N'Not Mention', N'My name is Manish Latch and I am a general dentist at Smile Dental. I currently work at the Henderson, Kelston, and Te Atatu branches. I am originally from India and moved to Auckland over 20 years ago.  I graduated from the University of Otago in December 2018. For many, going to the dentist is a scary thought. However, I believe it doesn’t have to be this way. It can be an empowering and positive experience and that’s what I aim to provide each time a patient walks into the clinic. I provide a full range of dental services, with a particular interest in endodontic and restorative treatment. I always aim to provide gold standard treatment to my patients. I believe a holistic approach must be taken in dentistry which is why I don’t just treat the tooth, but the patient. I ensure my patients are comfortable and fully informed. This is done by taking time with my approach and incorporating humour into my appointments. Laughter is the best medicine isn’t it? When I’m not working I have a wide range of hobbies that keep me occupied in my free time. These include playing sports and music to name a few.', N'.png')
GO
INSERT [dbo].[Dentists] ([DentistID], [DentistName], [Title], [Education], [Language], [Interest], [About], [Extension]) VALUES (14, N'Dr. Ala Al-Attar', N'Dentist', N'Not Mention', N'English', N'Oral surgery , Wisdom tooth extraction', N'I have more than 30 years of experience in all facets of general dentistry with special interest in oral surgery and wisdom tooth extraction, My experience enclodes more than 12 years in New Zealand and Australia. 
I love working with the Smile Dental team as they provide a lovely working environment and excellent dental care for clients.  I am registered with the Dental Council of New Zealand and a member of the New Zealand Dental Association. In addition to this I am registered with the Australian Dental Board. I have also been a lecturer and student supervisor for fifth year dental students at the University of Queensland School of Dentistry.', N'.jpg')
GO
SET IDENTITY_INSERT [dbo].[Dentists] OFF
GO
SET IDENTITY_INSERT [dbo].[Testimonials] ON 
GO
INSERT [dbo].[Testimonials] ([TestimonialID], [Name], [TestimonialText], [TestimonialDate], [Rating]) VALUES (1, N'Joan Pinto', N'Dr. Kevin is an excellent dentist. His manner is very professional. He is a caring, compassionate person. He explained everything in simple language so I could understand what want was going to happen. I am very pleased with my ongoing treatment. Manmeet, the practice manager was also very friendly and helpful. I will definitely continue giving them my business.', CAST(N'2021-05-14T00:47:59.3543754' AS DateTime2), 5)
GO
INSERT [dbo].[Testimonials] ([TestimonialID], [Name], [TestimonialText], [TestimonialDate], [Rating]) VALUES (2, N'Prachi Desai', N'Smile Dental is just fantastic. The staff are friendly and welcoming. Dental visits can be daunting, but the environment here will make you feel at ease. I would like to extend a special thanks to Dr. Boris. He is one of the kindest people I have met and he made me feel extremely comfortable during my previous visits. ', CAST(N'2021-05-14T00:48:43.4372077' AS DateTime2), 5)
GO
INSERT [dbo].[Testimonials] ([TestimonialID], [Name], [TestimonialText], [TestimonialDate], [Rating]) VALUES (3, N'Sophie Hunt', N'Awesome service. I didn’t have to wait long to be served and efficient check up. Very informative and they took the time to listen to my concerns and give me advice. They show great empathy for their patients. Definitely recommend.', CAST(N'2021-05-14T00:49:09.5504486' AS DateTime2), 5)
GO
SET IDENTITY_INSERT [dbo].[Testimonials] OFF
GO
